language: python

python:
  - "3.5.2"

sudo: false

# command to install dependencies
install:
  - travis_retry python setup.py dev
  - "pip install -r requirements.txt"


# command to run tests
script:
  - "nosetests"

notifications:
  email: false